// <auto-generated />
using System;
using FUNBIDE.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FUNBIDE.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FunbideDbContext))]
    [Migration("20260703192101_RediseñarPacientes")]
    partial class RediseñarPacientes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("funbide")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FUNBIDE.Domain.Entities.AuditoriaLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("CodigoRespuestaHttp")
                        .HasColumnType("integer");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("detalle");

                    b.Property<string>("Recurso")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset>("RegistradoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Detalle");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Detalle"), "gin");

                    b.HasIndex("Recurso");

                    b.HasIndex("RegistradoEn");

                    b.ToTable("auditoria_logs", "funbide");
                });

            modelBuilder.Entity("FUNBIDE.Domain.Entities.Cita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NotasCierre")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId", "Estado");

                    b.ToTable("citas", "funbide");
                });

            modelBuilder.Entity("FUNBIDE.Domain.Entities.Empleado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cargo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("NombreCompleto");

                    b.ToTable("empleados", "funbide");
                });

            modelBuilder.Entity("FUNBIDE.Domain.Entities.EntradaHistorialClinico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CitaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("contenido");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RegistradoEn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Contenido");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Contenido"), "gin");

                    b.HasIndex("PacienteId");

                    b.HasIndex("RegistradoEn");

                    b.ToTable("historial_clinico", "funbide");
                });

            modelBuilder.Entity("FUNBIDE.Domain.Entities.InventarioItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("StockActual")
                        .HasColumnType("integer");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("inventario_items", "funbide", t =>
                        {
                            t.HasCheckConstraint("ck_inventario_stock_no_negativo", "\"StockActual\" >= 0");
                        });
                });

            modelBuilder.Entity("FUNBIDE.Domain.Entities.MovimientoFinanciero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CitaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTimeOffset>("RegistradoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RegistradoEn");

                    b.ToTable("movimientos_financieros", "funbide", t =>
                        {
                            t.HasCheckConstraint("ck_movimiento_financiero_monto_positivo", "\"Monto\" > 0");
                        });
                });

            modelBuilder.Entity("FUNBIDE.Domain.Entities.MovimientoInventario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<Guid>("InventarioItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Referencia")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("RegistradoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StockResultante")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InventarioItemId");

                    b.ToTable("movimientos_inventario", "funbide");
                });

            modelBuilder.Entity("FUNBIDE.Domain.Entities.Paciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("documento_identidad");

                    b.Property<string>("FotoCedulaPath")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Documento")
                        .IsUnique();

                    b.HasIndex("Nombre", "Apellido");

                    b.ToTable("pacientes", "funbide");
                });

            modelBuilder.Entity("FUNBIDE.Domain.Entities.ResumenDiario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("DineroMovido")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("PacientesAtendidos")
                        .HasColumnType("integer");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Fecha")
                        .IsUnique();

                    b.ToTable("resumenes_diarios", "funbide");
                });

            modelBuilder.Entity("FUNBIDE.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("EliminadoPermanentemente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("FotoPerfilUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("SupabaseUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("SupabaseUserId")
                        .IsUnique();

                    b.ToTable("usuarios", "funbide");
                });

            modelBuilder.Entity("FUNBIDE.Domain.Entities.Cita", b =>
                {
                    b.OwnsOne("FUNBIDE.Domain.ValueObjects.IntervaloCita", "Intervalo", b1 =>
                        {
                            b1.Property<Guid>("CitaId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("Fin")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("fin");

                            b1.Property<DateTimeOffset>("Inicio")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("inicio");

                            b1.HasKey("CitaId");

                            b1.ToTable("citas", "funbide");

                            b1.WithOwner()
                                .HasForeignKey("CitaId");
                        });

                    b.Navigation("Intervalo");
                });

            modelBuilder.Entity("FUNBIDE.Domain.Entities.MovimientoInventario", b =>
                {
                    b.HasOne("FUNBIDE.Domain.Entities.InventarioItem", null)
                        .WithMany()
                        .HasForeignKey("InventarioItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
