// <auto-generated />
using System;
using FUNBIDE.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FUNBIDE.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FunbideDbContext))]
    [Migration("20260802215026_AgregarTarifarioProcedimiento")]
    partial class AgregarTarifarioProcedimiento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("funbide")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FUNBIDE.Domain.Entities.AuditoriaLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("CodigoRespuestaHttp")
                        .HasColumnType("integer");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("detalle");

                    b.Property<string>("Recurso")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset>("RegistradoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Detalle");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Detalle"), "gin");

                    b.HasIndex("Recurso");

                    b.HasIndex("RegistradoEn");

                    b.ToTable("auditoria_logs", "funbide");
                });

            modelBuilder.Entity("FUNBIDE.Domain.Entities.Cita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NotasCierre")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId", "Estado");

                    b.ToTable("citas", "funbide");
                });

            modelBuilder.Entity("FUNBIDE.Domain.Entities.Cobro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CitaId")
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoAutorizacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("MontoCobertura")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("MontoPagado")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(12,2)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("PorcentajeCobertura")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTimeOffset>("RegistradoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SeguroMedicoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TarifarioProcedimientoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TurnoCajaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CitaId");

                    b.HasIndex("PacienteId");

                    b.HasIndex("RegistradoEn");

                    b.HasIndex("TurnoCajaId");

                    b.ToTable("cobros", "funbide", t =>
                        {
                            t.HasCheckConstraint("ck_cobro_monto_pagado_no_negativo", "\"MontoPagado\" >= 0");

                            t.HasCheckConstraint("ck_cobro_monto_total_positivo", "\"MontoTotal\" > 0");
                        });
                });

            modelBuilder.Entity("FUNBIDE.Domain.Entities.ConfiguracionSistema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ActualizadoPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<bool>("ModoMantenimientoActivo")
                        .HasColumnType("boolean");

                    b.Property<string>("ModoMantenimientoMensaje")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("SesionesRevocadasEn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("configuracion_sistema", "funbide");
                });

            modelBuilder.Entity("FUNBIDE.Domain.Entities.Donacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("DonanteContacto")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DonanteNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTimeOffset>("RegistradoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RegistradoEn");

                    b.ToTable("donaciones", "funbide", t =>
                        {
                            t.HasCheckConstraint("ck_donacion_monto_positivo", "\"Monto\" > 0");
                        });
                });

            modelBuilder.Entity("FUNBIDE.Domain.Entities.Empleado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cargo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("NombreCompleto");

                    b.ToTable("empleados", "funbide");
                });

            modelBuilder.Entity("FUNBIDE.Domain.Entities.EntradaHistorialClinico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CitaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("contenido");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RegistradoEn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Contenido");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Contenido"), "gin");

                    b.HasIndex("PacienteId");

                    b.HasIndex("RegistradoEn");

                    b.ToTable("historial_clinico", "funbide");
                });

            modelBuilder.Entity("FUNBIDE.Domain.Entities.InventarioItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("StockActual")
                        .HasColumnType("integer");

                    b.Property<int>("StockMinimo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("inventario_items", "funbide", t =>
                        {
                            t.HasCheckConstraint("ck_inventario_stock_no_negativo", "\"StockActual\" >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("2f1a1a2a-0001-4a3e-8a9a-000000000001"),
                            Categoria = "Medicamento",
                            Codigo = "MED-001",
                            Nombre = "Acetaminofén 500mg",
                            StockActual = 320,
                            StockMinimo = 100
                        },
                        new
                        {
                            Id = new Guid("2f1a1a2a-0001-4a3e-8a9a-000000000002"),
                            Categoria = "Medicamento",
                            Codigo = "MED-002",
                            Nombre = "Ibuprofeno 400mg",
                            StockActual = 40,
                            StockMinimo = 80
                        },
                        new
                        {
                            Id = new Guid("2f1a1a2a-0001-4a3e-8a9a-000000000003"),
                            Categoria = "Medicamento",
                            Codigo = "MED-003",
                            Nombre = "Amoxicilina 500mg",
                            StockActual = 150,
                            StockMinimo = 60
                        },
                        new
                        {
                            Id = new Guid("2f1a1a2a-0001-4a3e-8a9a-000000000004"),
                            Categoria = "Medicamento",
                            Codigo = "MED-004",
                            Nombre = "Loratadina 10mg",
                            StockActual = 25,
                            StockMinimo = 30
                        },
                        new
                        {
                            Id = new Guid("2f1a1a2a-0001-4a3e-8a9a-000000000005"),
                            Categoria = "Insumo",
                            Codigo = "INS-001",
                            Nombre = "Guantes de nitrilo (caja)",
                            StockActual = 60,
                            StockMinimo = 20
                        },
                        new
                        {
                            Id = new Guid("2f1a1a2a-0001-4a3e-8a9a-000000000006"),
                            Categoria = "Insumo",
                            Codigo = "INS-002",
                            Nombre = "Jeringas 5ml",
                            StockActual = 15,
                            StockMinimo = 40
                        },
                        new
                        {
                            Id = new Guid("2f1a1a2a-0001-4a3e-8a9a-000000000007"),
                            Categoria = "Insumo",
                            Codigo = "INS-003",
                            Nombre = "Gasas estériles (paquete)",
                            StockActual = 90,
                            StockMinimo = 30
                        });
                });

            modelBuilder.Entity("FUNBIDE.Domain.Entities.MovimientoFinanciero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CitaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTimeOffset>("RegistradoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("TurnoCajaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RegistradoEn");

                    b.HasIndex("TurnoCajaId");

                    b.ToTable("movimientos_financieros", "funbide", t =>
                        {
                            t.HasCheckConstraint("ck_movimiento_financiero_monto_positivo", "\"Monto\" > 0");
                        });
                });

            modelBuilder.Entity("FUNBIDE.Domain.Entities.MovimientoInventario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<Guid>("InventarioItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Referencia")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("RegistradoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StockResultante")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InventarioItemId");

                    b.ToTable("movimientos_inventario", "funbide");
                });

            modelBuilder.Entity("FUNBIDE.Domain.Entities.Paciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Condicion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("documento_identidad");

                    b.Property<int?>("Edad")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Activo");

                    b.Property<string>("FotoCedulaPath")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateOnly?>("UltimaVisita")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("Documento")
                        .IsUnique();

                    b.HasIndex("Nombre", "Apellido");

                    b.ToTable("pacientes", "funbide");
                });

            modelBuilder.Entity("FUNBIDE.Domain.Entities.PermisoUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ActualizadoPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Concedido")
                        .HasColumnType("boolean");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Modulo")
                        .IsUnique();

                    b.ToTable("permisos_usuario", "funbide");
                });

            modelBuilder.Entity("FUNBIDE.Domain.Entities.ResumenDiario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("DineroMovido")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("PacientesAtendidos")
                        .HasColumnType("integer");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Fecha")
                        .IsUnique();

                    b.ToTable("resumenes_diarios", "funbide");
                });

            modelBuilder.Entity("FUNBIDE.Domain.Entities.SeguroMedico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("PorcentajeCobertura")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("seguros_medicos", "funbide", t =>
                        {
                            t.HasCheckConstraint("ck_seguro_medico_porcentaje_cobertura_rango", "\"PorcentajeCobertura\" > 0 AND \"PorcentajeCobertura\" <= 100");
                        });
                });

            modelBuilder.Entity("FUNBIDE.Domain.Entities.TarifarioProcedimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MontoPaciente")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MontoSeguro")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Procedimiento")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("SeguroMedicoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SeguroMedicoId", "Plan", "Procedimiento")
                        .IsUnique();

                    b.ToTable("tarifario_procedimientos", "funbide");
                });

            modelBuilder.Entity("FUNBIDE.Domain.Entities.TurnoCaja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AbiertoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CerradoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Diferencia")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("MontoEsperado")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("MontoFinalContado")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("MontoInicial")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Notas")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("UsuarioAperturaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioCierreId")
                        .HasColumnType("uuid");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Estado")
                        .IsUnique()
                        .HasFilter("\"Estado\" = 'Abierto'");

                    b.ToTable("turnos_caja", "funbide", t =>
                        {
                            t.HasCheckConstraint("ck_turno_caja_monto_inicial_no_negativo", "\"MontoInicial\" >= 0");
                        });
                });

            modelBuilder.Entity("FUNBIDE.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("EliminadoPermanentemente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Especialidad")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("FotoPerfilUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("SupabaseUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.HasIndex("SupabaseUserId")
                        .IsUnique();

                    b.ToTable("usuarios", "funbide");
                });

            modelBuilder.Entity("FUNBIDE.Infrastructure.Security.CredencialLocal", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("UsuarioId");

                    b.ToTable("credenciales_locales", "funbide");
                });

            modelBuilder.Entity("FUNBIDE.Domain.Entities.Cita", b =>
                {
                    b.OwnsOne("FUNBIDE.Domain.ValueObjects.IntervaloCita", "Intervalo", b1 =>
                        {
                            b1.Property<Guid>("CitaId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("Fin")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("fin");

                            b1.Property<DateTimeOffset>("Inicio")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("inicio");

                            b1.HasKey("CitaId");

                            b1.ToTable("citas", "funbide");

                            b1.WithOwner()
                                .HasForeignKey("CitaId");
                        });

                    b.Navigation("Intervalo");
                });

            modelBuilder.Entity("FUNBIDE.Domain.Entities.MovimientoInventario", b =>
                {
                    b.HasOne("FUNBIDE.Domain.Entities.InventarioItem", null)
                        .WithMany()
                        .HasForeignKey("InventarioItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FUNBIDE.Domain.Entities.PermisoUsuario", b =>
                {
                    b.HasOne("FUNBIDE.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
